Mongodb copy update
apostrophecms/apostrophe-multisite pull request #56
Opened 2021-03-08 18:52 UTC by gregvanbrug

Because the `copydb` command was deprecated in mongodb >= 4.2.x, copying a site from the Assembly dashboard was not working.

2021-03-08 20:30 UTC, boutell requested changes

2021-03-08 20:30 UTC, boutell commented on lib/sites-base.js
> +          const fromUri = `${baseUri}/${fromDb}`;
An issue I mentioned before: `fromUri` might already have a database name in it (definitely will in production). You will need to parse it, set a new `path`, and convert it back to a string.

2021-03-08 20:30 UTC, boutell commented on lib/sites-base.js
> +          const fromUri = `${baseUri}/${fromDb}`;
`baseUri` might, rather, thus the problem assembling `fromUri` and `toUri` in this naive way like I was able to get away with for the demo site.

2021-03-08 20:41 UTC, gregvanbrug commented on index.js
> +  self.mongodbUrl = options.mongodbUrl;
Its here: https://github.com/apostrophecms/apostrophe-multisite/blob/35901ba1b7ae53c845bd1a590c523f9ad676d95c/lib/sites-base.js#L289

The example you had sent included an options object in multisite which contains the mongodbUrl. I didn't see the mongodbUrl in the A2 version of multisite so just tacked this on. Could add options for parity ( or maybe the url is somewhere else i missed ).

2021-03-09 14:37 UTC, boutell commented
@gregvanbrug please review my new commits here. Thanks!

2021-03-09 15:45 UTC, boutell approved these changes

2021-03-09 15:45 UTC, merged